# Generated by Django 3.2.9 on 2021-11-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_2',
        ),
    ]
