# Generated by Django 3.2.9 on 2021-11-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20211118_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
