# Generated by Django 3.2.9 on 2021-11-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20211118_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
